name: nothing
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.9, <4.0
  - jupyter
  - streamlit=1.18
  - numpy>=1.2
  - pandas>=1.4
  - scikit-learn>=1.2
  - pip
  - pip:
     - text2emotion
     - emoji==1.7
     - fuzzywuzzy
     - nltk
