name: nothing
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - jupyter
  - streamlit==1.18
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
     - text2emotion
     - emoji==1.7
     - fuzzywuzzy
     - nltk
